# Assignment_10.py — Using Pinecone to Retrieve Top 3 Most Similar Product Records
# Author: Generated by M365 Copilot
# Date: 2025-11-30
# Description:
#   - Initialize Pinecone (if available) and upsert sample product embeddings.
#   - Use Azure OpenAI embeddings when available; otherwise fall back to an offline BOW/TF-IDF-like embedding.
#   - Query for the Top-3 most similar products for a set of dummy queries (no input()).
#   - Write console-style outputs to a logs file for submission.
#   - Single .py file as required by the assignment brief.

from __future__ import annotations
import os
import math
import re
from dataclasses import dataclass
from typing import List, Dict, Tuple, Optional

LOGS_FILE = "assignment_10_logs.txt"
INDEX_NAME = "product-similarity-index"
DEFAULT_EMBED_MODEL = os.getenv("AZURE_DEPLOYMENT_NAME", "text-embedding-3-small")

# ------------------------------- Data ----------------------------------
PRODUCTS: List[Dict[str, str]] = [
    {"id": "prod1", "title": "Red T-Shirt", "description": "Comfortable cotton t-shirt in bright red"},
    {"id": "prod2", "title": "Blue Jeans", "description": "Stylish denim jeans with relaxed fit"},
    {"id": "prod3", "title": "Black Leather Jacket", "description": "Genuine leather jacket with classic style"},
    {"id": "prod4", "title": "White Sneakers", "description": "Comfortable sneakers perfect for daily wear"},
    {"id": "prod5", "title": "Green Hoodie", "description": "Warm hoodie made of organic cotton"},
]

DUMMY_QUERIES: List[str] = [
    "clothing item for summer",
    "leather outerwear",
    "shoes for daily walking",
]

# ----------------------- Embedding Provider ----------------------------
class EmbeddingProvider:
    """Produces embeddings using Azure OpenAI (if available) or offline fallback."""

    def __init__(self):
        self.mode = "offline"
        self.dimension: int = 0
        self._client = None
        try:
            from openai import AzureOpenAI  # type: ignore
            endpoint = os.getenv("AZURE_OPENAI_ENDPOINT")
            api_key = os.getenv("AZURE_OPENAI_API_KEY")
            if endpoint and api_key:
                self._client = AzureOpenAI(
                    api_version=os.getenv("AZURE_OPENAI_API_VERSION", "2024-07-01-preview"),
                    azure_endpoint=endpoint,
                    api_key=api_key,
                )
                # text-embedding-3-small -> 1536 dims
                self.dimension = 1536
                self.mode = "azure"
        except Exception:
            self.mode = "offline"

        # Offline vocab/cache
        self._vocab: Dict[str, int] = {}
        self._idf: Dict[str, float] = {}

    @staticmethod
    def _normalize(text: str) -> str:
        return re.sub(r"[^a-z0-9\s]", " ", text.lower())

    def _build_vocab(self, corpus: List[str]) -> None:
        # Build vocabulary and IDF
        docs_tokens: List[List[str]] = []
        for doc in corpus:
            toks = [t for t in self._normalize(doc).split() if t]
            docs_tokens.append(toks)
            for t in set(toks):
                self._vocab.setdefault(t, len(self._vocab))
        # Compute IDF
        N = len(docs_tokens)
        df: Dict[str, int] = {t: 0 for t in self._vocab}
        for toks in docs_tokens:
            uniq = set(toks)
            for t in uniq:
                df[t] += 1
        self._idf = {t: math.log((N + 1) / (df_t + 1)) + 1.0 for t, df_t in df.items()}
        self.dimension = len(self._vocab)

    def embed(self, text: str) -> List[float]:
        if self.mode == "azure" and self._client is not None:
            try:
                resp = self._client.embeddings.create(input=text, model=DEFAULT_EMBED_MODEL)
                return list(resp.data[0].embedding)
            except Exception:
                # failover to offline
                self.mode = "offline"
        # Offline TF-IDF-like vector
        if self.dimension == 0:
            # Build vocab from PRODUCTS + queries the first time
            corpus = [p["title"] + ". " + p.get("description", "") for p in PRODUCTS] + DUMMY_QUERIES
            self._build_vocab(corpus)
        vec = [0.0] * self.dimension
        toks = [t for t in self._normalize(text).split() if t]
        tf: Dict[str, int] = {}
        for t in toks:
            tf[t] = tf.get(t, 0) + 1
        for t, c in tf.items():
            idx = self._vocab.get(t)
            if idx is not None:
                vec[idx] = float(c) * self._idf.get(t, 1.0)
        # L2 normalize
        norm = math.sqrt(sum(v * v for v in vec)) or 1.0
        return [v / norm for v in vec]

# --------------------------- Index Abstractions -------------------------
@dataclass
class Match:
    id: str
    score: float

class LocalIndex:
    def __init__(self, dimension: int):
        self.dimension = dimension
        self._vectors: Dict[str, List[float]] = {}

    def upsert(self, items: List[Tuple[str, List[float]]]) -> None:
        for _id, vec in items:
            self._vectors[_id] = vec

    @staticmethod
    def _cosine(a: List[float], b: List[float]) -> float:
        return sum(x * y for x, y in zip(a, b)) / ((math.sqrt(sum(x * x for x in a)) or 1.0) * (math.sqrt(sum(y * y for y in b)) or 1.0))

    def query(self, vector: List[float], top_k: int = 3) -> List[Match]:
        results = [Match(_id, self._cosine(vector, vec)) for _id, vec in self._vectors.items()]
        results.sort(key=lambda m: m.score, reverse=True)
        return results[:top_k]

class PineconeIndex:
    def __init__(self, api_key: Optional[str], index_name: str, dimension: int):
        self.available = False
        self.index = None
        try:
            from pinecone import Pinecone, ServerlessSpec  # type: ignore
            if api_key:
                pc = Pinecone(api_key=api_key)
                names = [i["name"] for i in pc.list_indexes()]
                if index_name not in names:
                    pc.create_index(
                        name=index_name,
                        dimension=dimension,
                        spec=ServerlessSpec(cloud="aws", region="us-east-1"),
                    )
                self.index = pc.Index(index_name)
                self.available = True
        except Exception:
            self.available = False

    def upsert(self, items: List[Tuple[str, List[float]]]) -> None:
        if not self.available or self.index is None:
            return
        try:
            self.index.upsert(items)
        except Exception:
            pass

    def query(self, vector: List[float], top_k: int = 3) -> List[Match]:
        if not self.available or self.index is None:
            return []
        try:
            res = self.index.query(vector=vector, top_k=top_k, include_metadata=False)
            return [Match(m.id, float(m.score)) for m in res.matches]
        except Exception:
            return []

# ---------------------------- Coordinator ------------------------------
class ProductSimilarityApp:
    def __init__(self):
        self.embedder = EmbeddingProvider()
        pinecone_key = os.getenv("PINECONE_API_KEY")
        if pinecone_key and self.embedder.mode == "azure":
            self.index = PineconeIndex(pinecone_key, INDEX_NAME, self.embedder.dimension)
            if not getattr(self.index, 'available', False):
                self.index = LocalIndex(self.embedder.dimension)
        else:
            self.index = LocalIndex(self.embedder.dimension or 1536)

    def prepare_vectors(self) -> List[Tuple[str, List[float]]]:
        items: List[Tuple[str, List[float]]] = []
        for p in PRODUCTS:
            text = f"{p['title']}. {p.get('description','')}"
            vec = self.embedder.embed(text)
            items.append((p["id"], vec))
        return items

    def run_queries(self, queries: List[str], top_k: int = 3) -> str:
        logs: List[str] = []
        engine = "Pinecone" if isinstance(self.index, PineconeIndex) and getattr(self.index, 'available', False) else "LocalIndex"
        logs.append("Using Pinecone to Retrieve Top 3 Most Similar Product Records — Demo Run")
        logs.append(f"Embedding mode: {self.embedder.mode} | Dimension: {self.embedder.dimension}")
        logs.append(f"Index engine: {engine} | Index name: {INDEX_NAME}\n")
        items = self.prepare_vectors()
        self.index.upsert(items)
        logs.append("Upserted product vectors: " + ", ".join([i[0] for i in items]))
        for q in queries:
            q_vec = self.embedder.embed(q)
            matches = self.index.query(q_vec, top_k=top_k)
            logs.append(f"\nTop {top_k} similar products for the query: '{q}'")
            for m in matches:
                prod = next(p for p in PRODUCTS if p["id"] == m.id)
                logs.append(f"- {prod['title']} (Similarity score: {m.score:.4f})")
        return "\n".join(logs)


def run_demo() -> None:
    app = ProductSimilarityApp()
    logs = app.run_queries(DUMMY_QUERIES, top_k=3)
    with open(LOGS_FILE, "w", encoding="utf-8") as f:
        f.write(logs)
    print(f"Done. Wrote demo results to {LOGS_FILE}")


if __name__ == "__main__":
    run_demo()
