# Assignment_13.py — Patient Information Collection & Advisory Chatbot Agent
# Author: Generated by M365 Copilot
# Date: 2025-11-30
# Description:
#   - Chatbot agent that collects patient information (name, age, symptoms) and provides preliminary advice.
#   - Uses LangGraph + AzureChatOpenAI when available; falls back to an offline rule-based engine otherwise.
#   - Includes dummy input dialogues (NO input()) and writes sample outputs to a logs file.
#   - Single .py file as required.

from __future__ import annotations
import os
import re
from dataclasses import dataclass, field
from typing import List, Dict, Optional

LOGS_FILE = "assignment_13_logs.txt"

# ----------------------------- Data Models -----------------------------
@dataclass
class PatientRecord:
    name: Optional[str] = None
    age: Optional[int] = None
    symptoms: List[str] = field(default_factory=list)

# ----------------------------- Utilities -------------------------------
SYMPTOM_RULES: Dict[str, str] = {
    "sore throat": "Drink warm fluids, avoid cold beverages; consider salt-water gargle.",
    "fever": "If < 38.5°C: rest and hydrate; if persistent/high, consult a clinician.",
    "dizziness": "Check blood pressure and hydration; avoid sudden standing.",
    "cough": "If > 2 weeks: evaluate for infections or allergies; consider humidified air.",
    "fatigue": "Assess sleep quality; consider iron deficiency; maintain balanced diet.",
}

SYMPTOM_KEYWORDS = list(SYMPTOM_RULES.keys())

def extract_age(text: str) -> Optional[int]:
    m = re.search(r"\b(\d{1,3})\s*(?:y(?:ears)?\s*old)?\b", text.lower())
    if m:
        try:
            age = int(m.group(1))
            if 0 < age < 120:
                return age
        except ValueError:
            return None
    return None

def extract_name(text: str) -> Optional[str]:
    # naive name extraction: "I'm <Name>" or "My name is <Name>"
    m = re.search(r"\b(?:i\s*am|i'm|my\s*name\s*is)\s+([A-Z][a-zA-Z]+(?:\s+[A-Z][a-zA-Z]+)*)", text)
    if m:
        return m.group(1).strip()
    return None

def extract_symptoms(text: str) -> List[str]:
    found = []
    t = text.lower()
    for s in SYMPTOM_KEYWORDS:
        if s in t:
            found.append(s)
    # also catch simple keywords
    if "throat" in t and "sore throat" not in found:
        found.append("sore throat")
    if "cough" in t and "cough" not in found:
        found.append("cough")
    if "fever" in t and "fever" not in found:
        found.append("fever")
    if "dizzy" in t and "dizziness" not in found:
        found.append("dizziness")
    if "tired" in t or "fatigue" in t:
        if "fatigue" not in found:
            found.append("fatigue")
    return list(dict.fromkeys(found))

# ------------------------- Offline Advisor -----------------------------
class OfflineAdvisor:
    @staticmethod
    def advise(rec: PatientRecord) -> List[str]:
        adv = []
        if rec.age is not None:
            if rec.age < 12:
                adv.append("For children, consult pediatric guidelines and avoid self-medication.")
            elif rec.age > 65:
                adv.append("For older adults, monitor hydration and blood pressure; seek care if symptoms persist.")
        for s in rec.symptoms:
            rule = SYMPTOM_RULES.get(s)
            if rule:
                adv.append(f"{s.capitalize()}: {rule}")
        if not adv:
            adv.append("General advice: rest, hydrate, and monitor symptoms; seek medical care if they worsen.")
        return adv

# ------------------------- LLM (Optional) -------------------------------
class AzureLLMAdvisor:
    def __init__(self):
        self.available = False
        self.llm = None
        try:
            from langchain_openai import AzureChatOpenAI  # type: ignore
            endpoint = os.getenv("AZURE_OPENAI_ENDPOINT")
            api_key = os.getenv("AZURE_OPENAI_API_KEY")
            deployment = os.getenv("AZURE_DEPLOYMENT_NAME") or "GPT-4o-mini"
            if endpoint and api_key:
                self.llm = AzureChatOpenAI(
                    azure_endpoint=endpoint,
                    azure_deployment=deployment,
                    api_key=api_key,
                    api_version=os.getenv("AZURE_OPENAI_API_VERSION", "2024-07-01-preview"),
                )
                self.available = True
        except Exception:
            self.available = False

    def advise(self, rec: PatientRecord) -> List[str]:
        if not self.available or self.llm is None:
            return OfflineAdvisor.advise(rec)
        try:
            prompt = (
                "You are a medical assistant (not a substitute for professional care). Based on the patient info, "
                "provide brief preliminary advice in bullet points, focusing on hydration, rest, observation, and "
                "when to seek medical attention. Avoid prescribing medications."
            )
            messages = [
                {"role": "system", "content": prompt},
                {"role": "user", "content": f"Patient: name={rec.name}, age={rec.age}, symptoms={', '.join(rec.symptoms)}"},
            ]
            out = self.llm.invoke(messages)
            text = out.content if hasattr(out, "content") else str(out)
            # Split bullets
            bullets = [b.strip("- • ") for b in text.splitlines() if b.strip()]
            return bullets[:6] or OfflineAdvisor.advise(rec)
        except Exception:
            return OfflineAdvisor.advise(rec)

# ----------------------------- Workflows -------------------------------
DUMMY_DIALOGUES: List[List[str]] = [
    [
        "Hi, I'm An. I'm 28 years old.",
        "I feel tired and have a sore throat since yesterday.",
    ],
    [
        "Hello, my name is Trang, 45 years old.",
        "I've had a persistent cough for about 3 weeks.",
    ],
    [
        "I'm Minh, 70 years old.",
        "Feeling dizzy today and a mild fever.",
    ],
]


def run_demo() -> None:
    advisor = AzureLLMAdvisor()
    logs: List[str] = []
    logs.append("Patient Information Collection & Advisory Chatbot — Demo Run")
    logs.append(f"LLM Available: {advisor.available}\n")

    for i, dialogue in enumerate(DUMMY_DIALOGUES, start=1):
        rec = PatientRecord()
        logs.append(f"=== Sample {i} ===")
        for utt in dialogue:
            logs.append(f"User: {utt}")
            # Extract signals from each utterance
            name = extract_name(utt)
            if name and not rec.name:
                rec.name = name
            age = extract_age(utt)
            if age and not rec.age:
                rec.age = age
            rec.symptoms.extend(extract_symptoms(utt))
        # Deduplicate symptoms
        rec.symptoms = list(dict.fromkeys(rec.symptoms))

        # Advisory
        adv = advisor.advise(rec)
        logs.append(f"Collected: name={rec.name}, age={rec.age}, symptoms={', '.join(rec.symptoms) or 'N/A'}")
        logs.append("Preliminary Advice:")
        for a in adv:
            logs.append(f"- {a}")
        logs.append("")

    with open(LOGS_FILE, "w", encoding="utf-8") as f:
        f.write("\n".join(logs))
    print(f"Done. Wrote demo results to {LOGS_FILE}")


if __name__ == "__main__":
    run_demo()
