# Assignment_14.py — Retail RAG Chatbot for Product & Policy Support
# Author: Generated by M365 Copilot
# Date: 2025-11-30
# Description:
#   - Retrieval-Augmented Generation (RAG) chatbot for retail product/policy support.
#   - Uses Azure OpenAI embeddings + chat model when available; otherwise falls back to
#     an offline TF-IDF vectorizer and template-based answer generator.
#   - Contains 15 Walmart policy/product entries (in-memory) and runs dummy Q&A demos.
#   - Writes demo results (question, retrieved context, generated answer) to a logs file.
#   - Single .py file per assignment requirement.

from __future__ import annotations
import os
import math
import re
from dataclasses import dataclass
from typing import List, Dict, Tuple, Optional

LOGS_FILE = "assignment_14_logs.txt"

# ------------------------------- Data ----------------------------------
DOCS: List[str] = [
    "Walmart customers may return electronics within 30 days with a receipt and original packaging.",
    "Grocery items at Walmart can be returned within 90 days with proof of purchase, except perishable products.",
    "Walmart offers a 1-year warranty on most electronics and appliances. See product details for exceptions.",
    "Walmart Plus members get free shipping with no minimum order amount.",
    "Prescription medications purchased at Walmart are not eligible for return or exchange.",
    "Open-box items are eligible for return at Walmart within the standard return period, but must include all original accessories.",
    "If a Walmart customer does not have a receipt, most returns are eligible for store credit with valid photo identification.",
    "Walmart allows price matching for identical items found on Walmart.com and local competitor ads.",
    "Walmart Vision Center purchases may be returned or exchanged within 60 days with a receipt.",
    "Returns on cell phones at Walmart require the device to be unlocked and all personal data erased.",
    "Walmart gift cards cannot be redeemed for cash except where required by law.",
    "Seasonal merchandise at Walmart (e.g., holiday decorations) may have modified return windows, see in-store signage.",
    "Bicycles purchased at Walmart can be returned within 90 days if not used outdoors and with all accessories present.",
    "For online Walmart orders, customers can return items in store or by mail using the prepaid label.",
    "Walmart reserves the right to deny returns suspected of fraud or abuse.",
]

# ----------------------------- Embeddings ------------------------------
class EmbeddingProvider:
    """Provides embeddings via Azure OpenAI when available, else offline TF-IDF."""

    def __init__(self):
        self.mode = "offline"
        self.dimension: int = 0
        self._client = None
        # Attempt Azure embeddings via openai SDK
        try:
            from openai import AzureOpenAI  # type: ignore
            endpoint = os.getenv("AZURE_OPENAI_ENDPOINT")
            api_key = os.getenv("AZURE_OPENAI_API_KEY")
            if endpoint and api_key:
                self._client = AzureOpenAI(
                    api_version=os.getenv("AZURE_OPENAI_API_VERSION", "2024-07-01-preview"),
                    azure_endpoint=endpoint,
                    api_key=api_key,
                )
                # text-embedding-3-small -> 1536 dims
                self.dimension = 1536
                self.mode = "azure"
        except Exception:
            self.mode = "offline"
        # Offline vocab
        self._vocab: Dict[str, int] = {}
        self._idf: Dict[str, float] = {}
        if self.mode == "offline":
            self._build_vocab(DOCS)

    @staticmethod
    def _normalize(text: str) -> str:
        return re.sub(r"[^a-z0-9\s]", " ", text.lower())

    def _build_vocab(self, corpus: List[str]) -> None:
        docs_tokens: List[List[str]] = []
        for doc in corpus:
            toks = [t for t in self._normalize(doc).split() if t]
            docs_tokens.append(toks)
            for t in set(toks):
                self._vocab.setdefault(t, len(self._vocab))
        N = len(docs_tokens)
        df: Dict[str, int] = {t: 0 for t in self._vocab}
        for toks in docs_tokens:
            uniq = set(toks)
            for t in uniq:
                df[t] += 1
        self._idf = {t: math.log((N + 1) / (df_t + 1)) + 1.0 for t, df_t in df.items()}
        self.dimension = len(self._vocab)

    def embed(self, text: str) -> List[float]:
        if self.mode == "azure" and self._client is not None:
            try:
                model = os.getenv("AZURE_DEPLOYMENT_NAME", "text-embedding-3-small")
                resp = self._client.embeddings.create(input=text, model=model)
                return list(resp.data[0].embedding)
            except Exception:
                self.mode = "offline"
        # Offline TF-IDF-like vector
        vec = [0.0] * self.dimension
        toks = [t for t in self._normalize(text).split() if t]
        tf: Dict[str, int] = {}
        for t in toks:
            tf[t] = tf.get(t, 0) + 1
        for t, c in tf.items():
            idx = self._vocab.get(t)
            if idx is not None:
                vec[idx] = float(c) * self._idf.get(t, 1.0)
        # L2 normalize
        norm = math.sqrt(sum(v * v for v in vec)) or 1.0
        return [v / norm for v in vec]

# ------------------------------ Index ----------------------------------
@dataclass
class Match:
    doc_id: int
    score: float

class LocalIndex:
    def __init__(self, embedder: EmbeddingProvider):
        self.embedder = embedder
        self.doc_vectors: List[List[float]] = [self.embedder.embed(text) for text in DOCS]

    @staticmethod
    def _cosine(a: List[float], b: List[float]) -> float:
        return sum(x * y for x, y in zip(a, b)) / ((math.sqrt(sum(x * x for x in a)) or 1.0) * (math.sqrt(sum(y * y for y in b)) or 1.0))

    def query(self, q: str, k: int = 3) -> List[Match]:
        q_vec = self.embedder.embed(q)
        scores = [Match(i, self._cosine(q_vec, v)) for i, v in enumerate(self.doc_vectors)]
        scores.sort(key=lambda m: m.score, reverse=True)
        return scores[:k]

# ---------------------------- Generator --------------------------------
class Generator:
    def __init__(self):
        self.mode = "offline"
        self.client = None
        try:
            from openai import AzureOpenAI  # type: ignore
            endpoint = os.getenv("AZURE_OPENAI_ENDPOINT")
            api_key = os.getenv("AZURE_OPENAI_API_KEY")
            if endpoint and api_key:
                self.client = AzureOpenAI(
                    api_version=os.getenv("AZURE_OPENAI_API_VERSION", "2024-07-01-preview"),
                    azure_endpoint=endpoint,
                    api_key=api_key,
                )
                self.mode = "azure"
        except Exception:
            self.mode = "offline"

    def generate(self, question: str, context: str) -> str:
        system = (
            "You are a helpful retail support assistant. Answer the question using ONLY the provided context. "
            "Be concise, clearly state the policy, and mention any conditions."
        )
        if self.mode == "azure" and self.client is not None:
            try:
                model = os.getenv("AZURE_DEPLOYMENT_NAME", "GPT-4o-mini")
                messages = [
                    {"role": "system", "content": system},
                    {"role": "user", "content": f"Context:\n{context}\n\nQuestion: {question}"},
                ]
                resp = self.client.chat.completions.create(model=model, messages=messages, temperature=0.0, max_tokens=300)
                return resp.choices[0].message.content.strip()
            except Exception:
                pass
        # Offline template-based answer
        return (
            "Based on the policy information: "
            + context.replace("\n", " ")
            + " \n\nAnswer: "
            + "Please follow the stated return/warranty and conditions above. For edge cases, check in-store signage or contact customer service."
        )

# ------------------------------ App ------------------------------------
class RetailRAGApp:
    def __init__(self):
        self.embedder = EmbeddingProvider()
        self.index = LocalIndex(self.embedder)
        self.generator = Generator()

    def ask(self, question: str, k: int = 3) -> Tuple[str, str]:
        matches = self.index.query(question, k=k)
        context = "\n".join([f"- {DOCS[m.doc_id]}" for m in matches])
        answer = self.generator.generate(question, context)
        return context, answer

# --------------------------- Demo (dummy) -------------------------------
DUMMY_QUESTIONS: List[str] = [
    "Can I return a Walmart bicycle if I've ridden it once?",
    "What is the return window for electronics at Walmart?",
    "Does Walmart allow price matching with local competitors?",
    "Can I return prescription medications to Walmart?",
    "How do I return an online Walmart order?",
]


def run_demo() -> None:
    app = RetailRAGApp()
    logs: List[str] = []
    logs.append("Retail RAG Chatbot — Demo Run")
    logs.append(f"Embedding mode: {app.embedder.mode} | dim={app.embedder.dimension}")
    logs.append(f"Generator mode: {app.generator.mode}\n")

    for i, q in enumerate(DUMMY_QUESTIONS, start=1):
        context, answer = app.ask(q, k=3)
        logs.append(f"=== Q{i} ===")
        logs.append(f"User Question:\n  {q}")
        logs.append("Retrieved Context:\n" + indent(context, "  "))
        logs.append("Generated Answer:\n" + indent(answer, "  "))
        logs.append("")

    with open(LOGS_FILE, "w", encoding="utf-8") as f:
        f.write("\n".join(logs))
    print(f"Done. Wrote demo results to {LOGS_FILE}")


if __name__ == "__main__":
    run_demo()
