# Assignment_12.py — Satellite Image Cloud Detection via AzureOpenAI Inference
# Author: Generated by M365 Copilot
# Date: 2025-11-30
# Description:
#   - Lightweight script to classify satellite images as "Cloudy" or "Clear" using Azure OpenAI multimodal inference.
#   - Uses 3 mock image URLs (NO input()). Prints logs to console and can write to a logs file.
#   - If Azure or network is unavailable, falls back to a simple offline image heuristic (brightness/whiteness ratio).
#   - Single .py file per assignment requirement.

from __future__ import annotations
import os
import io
import base64
import math
import traceback
from typing import List, Dict, Optional

# External deps (optional at runtime): requests, pillow (PIL), openai OR langchain-openai
try:
    import requests  # type: ignore
except Exception:
    requests = None

try:
    from PIL import Image  # type: ignore
except Exception:
    Image = None

LOGS_FILE = "assignment_12_logs.txt"
DEFAULT_MODEL = os.getenv("AZURE_DEPLOYMENT_NAME", "GPT-4o-mini")
DEFAULT_API_VERSION = os.getenv("AZURE_OPENAI_API_VERSION", "2024-07-01-preview")

# ----------------------------- Dummy Inputs -----------------------------
IMAGE_URLS: List[str] = [
    # Cloudy sky
    "https://images.pexels.com/photos/53594/blue-clouds-day-fluffy-53594.jpeg?cs=srgb&dl=pexels-pixabay-53594.jpg&fm=jpg",
    # Clear scene (blue sky minimal clouds)
    "https://images.pexels.com/photos/281260/pexels-photo-281260.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260",
    # Mixed scene (some clouds)
    "https://images.pexels.com/photos/531972/pexels-photo-531972.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260",
]

# ------------------------- Utilities & Helpers --------------------------
def fetch_image_base64(url: str) -> Optional[str]:
    if requests is None:
        return None
    try:
        resp = requests.get(url, timeout=20)
        resp.raise_for_status()
        b64 = base64.b64encode(resp.content).decode("utf-8")
        # Try to infer content-type; default to jpeg
        ctype = resp.headers.get("Content-Type", "image/jpeg")
        if not ctype.startswith("image/"):
            ctype = "image/jpeg"
        return f"data:{ctype};base64,{b64}"
    except Exception:
        return None

# --------------------------- Azure Inference ----------------------------
class AzureLLM:
    def __init__(self):
        self.mode = "none"
        self.client = None
        self.langchain_llm = None
        endpoint = os.getenv("AZURE_OPENAI_ENDPOINT")
        api_key = os.getenv("AZURE_OPENAI_API_KEY")
        if endpoint and api_key:
            # Try LangChain first (structured output)
            try:
                from langchain_openai import AzureChatOpenAI  # type: ignore
                self.langchain_llm = AzureChatOpenAI(
                    azure_endpoint=endpoint,
                    azure_deployment=DEFAULT_MODEL,
                    api_key=api_key,
                    api_version=DEFAULT_API_VERSION,
                )
                self.mode = "langchain"
                return
            except Exception:
                self.langchain_llm = None
            # Fallback to AzureOpenAI SDK
            try:
                from openai import AzureOpenAI  # type: ignore
                self.client = AzureOpenAI(
                    api_version=DEFAULT_API_VERSION,
                    azure_endpoint=endpoint,
                    api_key=api_key,
                )
                self.mode = "azure"
            except Exception:
                self.client = None
                self.mode = "none"

    def classify(self, image_data_url: str) -> Dict[str, float | str]:
        """Return dict: {label: 'Cloudy'|'Clear', confidence: float} using Azure inference."""
        system_prompt = (
            "You are an imagery analyst. Based on the satellite image provided, classify the scene as either "
            "'Clear' (no clouds) or 'Cloudy' (with clouds). Respond with ONLY one word and a confidence percent."
        )
        user_text = "Classify the scene as either: 'Clear' or 'Cloudy' and provide an accuracy (percent)."
        if self.mode == "langchain" and self.langchain_llm is not None:
            try:
                from pydantic import BaseModel, Field  # type: ignore
                class WeatherResponse(BaseModel):
                    accuracy: float = Field(description="The accuracy percent")
                    result: str = Field(description="One of Clear or Cloudy")
                llm_struct = self.langchain_llm.with_structured_output(WeatherResponse)
                messages = [
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": [
                        {"type": "text", "text": user_text},
                        {"type": "image_url", "image_url": {"url": image_data_url}},
                    ]},
                ]
                out = llm_struct.invoke(messages)
                label = (out.result or "").strip().title()
                acc = float(out.accuracy or 0.0)
                if label not in {"Cloudy", "Clear"}:
                    label = "Cloudy" if acc >= 50 else "Clear"
                return {"label": label, "confidence": acc}
            except Exception:
                # Fall through to AzureOpenAI SDK
                pass
        if self.mode == "azure" and self.client is not None:
            try:
                messages = [
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": [
                        {"type": "text", "text": user_text},
                        {"type": "image_url", "image_url": {"url": image_data_url}},
                    ]},
                ]
                resp = self.client.chat.completions.create(
                    model=DEFAULT_MODEL,
                    messages=messages,
                    temperature=0.0,
                    max_tokens=20,
                )
                text = resp.choices[0].message.content.strip()
                # Parse e.g., "Cloudy 92.4%" or "Clear (accuracy: 88%)"
                lab = "Cloudy" if "cloud" in text.lower() else ("Clear" if "clear" in text.lower() else "Cloudy")
                import re
                m = re.search(r"(\d{1,3}(?:\.\d+)?)\s*%", text)
                acc = float(m.group(1)) if m else 50.0
                return {"label": lab, "confidence": acc}
            except Exception:
                return {"label": "Unknown", "confidence": 0.0}
        return {"label": "Unknown", "confidence": 0.0}

# ------------------------- Offline Heuristic ----------------------------
def offline_classify(image_data_url: str) -> Dict[str, float | str]:
    """Simple heuristic using pixel brightness & whiteness.
    If PIL or requests is missing, returns Unknown. Not a real model — for offline demo only.
    """
    if requests is None or Image is None:
        return {"label": "Unknown", "confidence": 0.0}
    try:
        # Decode data URL to bytes
        header, b64 = image_data_url.split(",", 1)
        content = base64.b64decode(b64)
        img = Image.open(io.BytesIO(content)).convert("RGB").resize((256, 256))
        # Compute brightness & near-white ratio
        pixels = img.getdata()
        bright_count = 0
        whiteish = 0
        total = len(pixels)
        for r, g, b in pixels:
            v = (max(r, g, b)) / 255.0
            s = (max(r, g, b) - min(r, g, b)) / (max(r, g, b) or 1)
            if v > 0.75:
                bright_count += 1
            # near-white threshold
            if r > 220 and g > 220 and b > 220:
                whiteish += 1
        bright_ratio = bright_count / total
        white_ratio = whiteish / total
        score = (bright_ratio * 0.6 + white_ratio * 0.4) * 100.0
        label = "Cloudy" if score > 40 else "Clear"
        return {"label": label, "confidence": round(score, 1)}
    except Exception:
        return {"label": "Unknown", "confidence": 0.0}

# ------------------------------- Main ----------------------------------
def run_batch(write_logs: bool = True) -> str:
    logs: List[str] = []
    llm = AzureLLM()
    logs.append("Satellite Image Cloud Detection — Batch Run")
    logs.append(f"Engine mode: {llm.mode}\n")

    for i, url in enumerate(IMAGE_URLS, start=1):
        logs.append(f"Image {i}: {url}")
        data_url = fetch_image_base64(url)
        if not data_url:
            logs.append("  [Error] Could not fetch image or convert to base64.")
            logs.append("")
            continue
        result = llm.classify(data_url)
        label = result.get("label", "Unknown")
        conf = result.get("confidence", 0.0)
        if label == "Unknown":
            result = offline_classify(data_url)
            label = result.get("label", "Unknown")
            conf = result.get("confidence", 0.0)
            logs.append("  Used offline heuristic.")
        logs.append(f"  Prediction: {label}")
        logs.append(f"  Confidence: {conf} %\n")

    output = "\n".join(logs)
    if write_logs:
        try:
            with open(LOGS_FILE, "w", encoding="utf-8") as f:
                f.write(output)
        except Exception:
            pass
    return output


if __name__ == "__main__":
    # No manual input; run over dummy URLs
    print(run_batch(write_logs=True))
