# Assignment_01.py — Command-Line Task Manager in Python
# Author: Generated by M365 Copilot
# Date: 2025-11-30
# Description:
#   - Simple task manager supporting add, view, complete, delete (and a few optional enhancements).
#   - Uses a dummy commands list (no interactive input()).
#   - Writes demo output to a logs file for submission.

from __future__ import annotations
import json
from typing import List, Dict, Tuple, Optional

LOGS_FILE = "assignment_01_logs.txt"
SAVE_FILE = "tasks_data.json"


class TaskManager:
    def __init__(self):
        self.tasks: List[Dict] = []

    def _next_id(self) -> int:
        return (self.tasks[-1]["id"] + 1) if self.tasks else 1

    def add_task(self, description: str) -> str:
        task = {"id": self._next_id(), "description": description.strip(), "completed": False}
        self.tasks.append(task)
        return f"Task '{description}' added with ID {task['id']}."

    def view_tasks(self) -> List[str]:
        if not self.tasks:
            return ["No tasks available."]
        lines = []
        for t in self.tasks:
            status = "Done" if t["completed"] else "Pending"
            lines.append(f"{t['id']}: {t['description']} [{status}]")
        return lines

    def mark_completed(self, task_id: int) -> str:
        for t in self.tasks:
            if t["id"] == task_id:
                t["completed"] = True
                return f"Task ID {task_id} marked as completed."
        return f"No task found with ID {task_id}."

    def delete_task(self, task_id: int) -> str:
        before = len(self.tasks)
        self.tasks = [t for t in self.tasks if t["id"] != task_id]
        after = len(self.tasks)
        return f"Task ID {task_id} deleted." if after < before else f"No task found with ID {task_id}."

    # --- Optional Enhancements ---
    def update_task(self, task_id: int, new_description: str) -> str:
        for t in self.tasks:
            if t["id"] == task_id:
                t["description"] = new_description.strip()
                return f"Task ID {task_id} updated."
        return f"No task found with ID {task_id}."

    def list_pending(self) -> List[str]:
        lines = [f"{t['id']}: {t['description']} [Pending]" for t in self.tasks if not t["completed"]]
        return lines or ["No pending tasks."]

    def list_done(self) -> List[str]:
        lines = [f"{t['id']}: {t['description']} [Done]" for t in self.tasks if t["completed"]]
        return lines or ["No completed tasks."]

    def save(self, path: str = SAVE_FILE) -> str:
        with open(path, "w", encoding="utf-8") as f:
            json.dump(self.tasks, f, ensure_ascii=False, indent=2)
        return f"Tasks saved to {path}."

    def load(self, path: str = SAVE_FILE) -> str:
        try:
            with open(path, "r", encoding="utf-8") as f:
                self.tasks = json.load(f)
            return f"Tasks loaded from {path}."
        except FileNotFoundError:
            return f"Save file {path} not found."


def execute_commands(tm: TaskManager, commands: List[Tuple[str, ...]]) -> str:
    """Execute a list of command tuples and return a multi-line string log."""
    logs: List[str] = []
    for cmd in commands:
        choice = cmd[0]
        logs.append(f"\n> {cmd}")
        if choice == "add":
            if len(cmd) > 1:
                logs.append(tm.add_task(cmd[1]))
            else:
                logs.append("Add command requires a description.")
        elif choice == "view":
            for line in tm.view_tasks():
                logs.append(line)
        elif choice == "complete":
            if len(cmd) > 1:
                try:
                    tid = int(cmd[1])
                    logs.append(tm.mark_completed(tid))
                except ValueError:
                    logs.append("Invalid task ID.")
            else:
                logs.append("Complete command requires a task ID.")
        elif choice == "delete":
            if len(cmd) > 1:
                try:
                    tid = int(cmd[1])
                    logs.append(tm.delete_task(tid))
                except ValueError:
                    logs.append("Invalid task ID.")
            else:
                logs.append("Delete command requires a task ID.")
        elif choice == "update":
            if len(cmd) > 2:
                try:
                    tid = int(cmd[1])
                    logs.append(tm.update_task(tid, cmd[2]))
                except ValueError:
                    logs.append("Invalid task ID.")
            else:
                logs.append("Update command requires a task ID and new description.")
        elif choice == "pending":
            for line in tm.list_pending():
                logs.append(line)
        elif choice == "done":
            for line in tm.list_done():
                logs.append(line)
        elif choice == "save":
            logs.append(tm.save())
        elif choice == "load":
            logs.append(tm.load())
        elif choice == "exit":
            logs.append("Exiting Task Manager. Goodbye!")
            break
        else:
            logs.append(f"Invalid command: {choice}")
    return "\n".join(logs)


def run_demo() -> None:
    tm = TaskManager()
    commands_to_execute: List[Tuple[str, ...]] = [
        ("add", "Buy groceries"),
        ("add", "Walk the dog"),
        ("view",),
        ("complete", "1"),
        ("view",),
        ("update", "2", "Walk the dog and water plants"),
        ("pending",),
        ("done",),
        ("delete", "2"),
        ("view",),
        ("save",),
        ("load",),
        ("exit",),
    ]
    logs = execute_commands(tm, commands_to_execute)
    with open(LOGS_FILE, "w", encoding="utf-8") as f:
        f.write("Command-Line Task Manager — Demo Logs\n")
        f.write(logs)


if __name__ == "__main__":
    run_demo()
