# Assignment_05.py — Build Resume Generation Using LLaMA3 (Local)
# Author: Generated by M365 Copilot
# Date: 2025-11-30
# Description:
#   - Generate professional resumes based on structured user inputs.
#   - Prefer local LLaMA (llama_cpp) if available and model path is provided.
#   - Fall back to an offline, deterministic template-based generator for portability.
#   - Uses dummy input list (NO input()).
#   - Produces 3 sample outputs and a logs file.
# Reference: Assignment brief requires single .py, dummy inputs, and sample outputs.

from __future__ import annotations
import os
import json
import re
import textwrap
from dataclasses import dataclass, field
from typing import List, Dict, Optional, Any

LOGS_FILE = "assignment_05_logs.txt"
OUTPUT_DIR = "resumes_output"
LLAMA_MODEL_ENV = "LLAMA_MODEL_PATH"  # optional env var pointing to local .gguf


# ----------------------------- Data Models -----------------------------
@dataclass
class Experience:
    title: str
    company: str
    location: str
    start: str  # e.g., "2023-01"
    end: str    # e.g., "2025-11" or "Present"
    bullets: List[str] = field(default_factory=list)

@dataclass
class Education:
    degree: str
    school: str
    year: str
    details: Optional[str] = None

@dataclass
class Project:
    name: str
    description: str
    tech: List[str] = field(default_factory=list)
    impact: Optional[str] = None

@dataclass
class CandidateProfile:
    name: str
    title: str
    email: str
    phone: str
    location: str
    links: Dict[str, str]  # e.g., {"GitHub": "...", "LinkedIn": "..."}
    summary: str
    skills: List[str]
    experience: List[Experience]
    education: List[Education]
    projects: List[Project] = field(default_factory=list)


# ----------------------- LLaMA (llama_cpp) Wrapper ---------------------
class LlamaEngine:
    """Lightweight wrapper around llama_cpp, if installed.

    Usage requires setting LLAMA_MODEL_PATH env var to a local GGUF model.
    """

    def __init__(self, model_path: Optional[str] = None, n_ctx: int = 4096):
        self.available = False
        self.llm = None
        self.model_path = model_path or os.getenv(LLAMA_MODEL_ENV)
        try:
            from llama_cpp import Llama  # type: ignore
            if self.model_path and os.path.exists(self.model_path):
                self.llm = Llama(model_path=self.model_path, n_ctx=n_ctx)
                self.available = True
        except Exception:
            self.available = False

    def generate(self, prompt: str, max_tokens: int = 768, temperature: float = 0.7) -> str:
        if not self.available:
            raise RuntimeError("LlamaEngine unavailable. Provide a valid GGUF model and llama_cpp.")
        try:
            out = self.llm(prompt, max_tokens=max_tokens, temperature=temperature)
            # llama_cpp returns dict with choices[0].text or choices[0].message.content depending on mode
            if isinstance(out, dict):
                if "choices" in out and out["choices"]:
                    choice = out["choices"][0]
                    return choice.get("text") or choice.get("message", {}).get("content", "").strip()
            return str(out)
        except Exception as e:
            raise RuntimeError(f"LLaMA generation failed: {e}")


# ----------------------- Offline Resume Generator ----------------------
class OfflineResumeGenerator:
    """Deterministic resume builder with simple tailoring to a job description."""

    def __init__(self, width: int = 96):
        self.width = width

    def tailor_skills(self, skills: List[str], job_desc: Optional[str]) -> List[str]:
        if not job_desc:
            return skills
        jd = job_desc.lower()
        scored = []
        for s in skills:
            kw = s.lower()
            score = sum(1 for token in re.split(r"[\s/,]+", kw) if token and token in jd)
            scored.append((s, score))
        # sort by score desc, then skill name
        scored.sort(key=lambda x: (-x[1], x[0].lower()))
        # emphasize top 8
        ordered = [s for s, _ in scored]
        top = ordered[:8]
        rest = [s for s in skills if s not in top]
        return top + rest

    def format_section(self, title: str) -> str:
        return f"\n{title}\n" + ("-" * len(title))

    def build(self, profile: CandidateProfile, job_desc: Optional[str] = None) -> str:
        # Header
        lines = [
            f"{profile.name} — {profile.title}",
            f"{profile.location} | {profile.email} | {profile.phone}",
            " | ".join([f"{k}: {v}" for k, v in profile.links.items()])
        ]
        lines.append(self.format_section("Summary"))
        lines.append(textwrap.fill(profile.summary, width=self.width))

        # Skills (tailored)
        skills_tailored = self.tailor_skills(profile.skills, job_desc)
        lines.append(self.format_section("Skills"))
        lines.append(textwrap.fill(", ".join(skills_tailored), width=self.width))

        # Experience
        lines.append(self.format_section("Experience"))
        for exp in profile.experience:
            header = f"{exp.title} | {exp.company} — {exp.location} ({exp.start} – {exp.end})"
            lines.append(header)
            for b in exp.bullets[:6]:
                lines.append(f"• {textwrap.fill(b, subsequent_indent='  ', width=self.width)}")

        # Projects
        if profile.projects:
            lines.append(self.format_section("Projects"))
            for p in profile.projects[:3]:
                head = f"{p.name} — Tech: {', '.join(p.tech)}"
                lines.append(head)
                lines.append(textwrap.fill(p.description, width=self.width))
                if p.impact:
                    lines.append(f"Impact: {textwrap.fill(p.impact, width=self.width)}")

        # Education
        lines.append(self.format_section("Education"))
        for edu in profile.education:
            row = f"{edu.degree} — {edu.school} ({edu.year})"
            if edu.details:
                row += f" | {edu.details}"
            lines.append(row)

        return "\n".join(lines)


# ----------------------- Coordinator / Facade --------------------------
class ResumeGenerator:
    def __init__(self, llama: Optional[LlamaEngine] = None):
        self.llama = llama or LlamaEngine()
        self.offline = OfflineResumeGenerator()

    def _build_prompt(self, profile: CandidateProfile, job_desc: Optional[str]) -> str:
        # Compose a structured prompt for LLM
        data = {
            "candidate": profile.__dict__
        }
        # Expand dataclasses inside
        data["candidate"]["experience"] = [e.__dict__ for e in profile.experience]
        data["candidate"]["education"] = [e.__dict__ for e in profile.education]
        data["candidate"]["projects"] = [p.__dict__ for p in profile.projects]

        instructions = (
            "You are a resume writing assistant. Generate a concise, ATS-friendly resume in plain text. "
            "Use clear sections: Summary, Skills, Experience, Projects (optional), Education. "
            "Bullet points should start with strong action verbs and include measurable impact. "
            "Tailor Skills and Summary to the provided job description."
        )
        return (
            f"{instructions}\n\nJob Description:\n{job_desc or 'N/A'}\n\nCandidate Data (JSON):\n{json.dumps(data, ensure_ascii=False, indent=2)}\n\nResume:""
        )

    def generate(self, profile: CandidateProfile, job_desc: Optional[str] = None,
                 use_llama: bool = True) -> Dict[str, Any]:
        engine = "LLaMA3 (llama_cpp)" if (use_llama and self.llama.available) else "Offline Template"
        try:
            if use_llama and self.llama.available:
                prompt = self._build_prompt(profile, job_desc)
                resume_text = self.llama.generate(prompt, max_tokens=1200, temperature=0.6)
            else:
                resume_text = self.offline.build(profile, job_desc)
            return {"engine": engine, "resume": resume_text}
        except Exception as e:
            # Fallback to offline on failure
            resume_text = self.offline.build(profile, job_desc)
            return {"engine": f"{engine} -> Fallback Offline", "resume": resume_text, "error": str(e)}


# ----------------------------- Samples ---------------------------------

def sample_profiles() -> List[Dict[str, Any]]:
    """Return 3 sample profiles & job descriptions."""
    p1 = CandidateProfile(
        name="Truong Vuong Van",
        title="Android Software Engineer (Automotive)",
        email="truong.vuong@example.com",
        phone="+84 90 000 0000",
        location="Hanoi, Vietnam",
        links={"GitHub": "https://github.com/truongvv", "LinkedIn": "https://linkedin.com/in/truongvv"},
        summary=(
            "Android engineer with experience in Android Automotive OS (AAOS), HVAC integrations, "
            "CarPropertyManager, and system diagnostics. Enjoys optimizing embedded UI/UX and "
            "ensuring compliance with ATS/CTS frameworks."
        ),
        skills=[
            "Android", "Kotlin", "Jetpack Compose", "Android Automotive OS", "HVAC", "CarPropertyManager",
            "MVVM", "MVI", "Coroutines", "Flow", "Room", "WorkManager", "AOSP", "CTS", "ATS", "Git", "CI/CD"
        ],
        experience=[
            Experience(
                title="Senior Android Engineer",
                company="FSOFT",
                location="Hanoi",
                start="2023-04",
                end="Present",
                bullets=[
                    "Implemented HVAC controls with CarPropertyManager, reducing latency by 25%.",
                    "Built AAOS UI modules using Jetpack Compose; improved rendering FPS by 18%.",
                    "Automated ATS/CTS test suites; cut manual regression time by 40%.",
                    "Diagnosed cold boot issues on emulator; improved boot stability across variants.",
                ],
            ),
            Experience(
                title="Android Developer",
                company="FA VN - IVI2",
                location="Hanoi",
                start="2021-01",
                end="2023-03",
                bullets=[
                    "Developed in-car infotainment features, integrating HVAC visualizations.",
                    "Optimized coroutine-based data flows reducing UI jank events by 30%.",
                ],
            ),
        ],
        education=[Education(degree="B.S. Computer Science", school="HUST", year="2018")],
        projects=[
            Project(
                name="AAOS HVAC Diagnostics",
                description="Toolkit to visualize and debug HVAC sensor properties in AAOS.",
                tech=["Kotlin", "Compose", "AAOS"],
                impact="Adopted by 2 internal teams; reduced issue triage time by 35%.",
            )
        ],
    )
    jd1 = (
        "Seeking Android Automotive engineer to develop HVAC and vehicle property integrations, "
        "optimize AAOS UI, and ensure CTS compliance. Experience with Kotlin, Jetpack Compose, and Coroutines required."
    )

    p2 = CandidateProfile(
        name="Nguyen Minh An",
        title="Python Data Engineer",
        email="minh.an@example.com",
        phone="+84 91 000 0000",
        location="HCMC, Vietnam",
        links={"GitHub": "https://github.com/minhan", "LinkedIn": "https://linkedin.com/in/minhan"},
        summary=(
            "Data engineer focused on pipelines, ETL, and analytics. Experience with Pandas, SQL, and cloud CI/CD."
        ),
        skills=["Python", "Pandas", "SQL", "Airflow", "ETL", "Docker", "CI/CD", "Linux", "Git"],
        experience=[
            Experience(
                title="Data Engineer",
                company="Tech Analytics",
                location="HCMC",
                start="2022-02",
                end="Present",
                bullets=[
                    "Built batch ETL pipelines with Airflow moving 50M+ rows/night.",
                    "Optimized Pandas workloads reducing job time from 2h to 50m.",
                ],
            ),
        ],
        education=[Education(degree="B.S. Information Systems", school="UEH", year="2020")],
        projects=[Project(name="Retail KPI Dashboard", description="End-to-end pipeline to compute KPIs.", tech=["Python", "SQL", "Airflow"])],
    )
    jd2 = "Hiring Data Engineer for ETL pipelines, Airflow scheduling, and SQL performance tuning."

    p3 = CandidateProfile(
        name="Pham Thu Trang",
        title="AI Product Manager",
        email="thu.trang@example.com",
        phone="+84 92 000 0000",
        location="Da Nang, Vietnam",
        links={"Portfolio": "https://pm-trang.example.com", "LinkedIn": "https://linkedin.com/in/trangpm"},
        summary=(
            "Product manager leading AI features from ideation to launch; experienced in prompt engineering and A/B testing."
        ),
        skills=["Product Strategy", "Prompt Engineering", "User Research", "A/B Testing", "Analytics", "Roadmapping"],
        experience=[
            Experience(
                title="Product Manager",
                company="AI Startup",
                location="Da Nang",
                start="2021-08",
                end="Present",
                bullets=[
                    "Shipped LLM-powered summarizer driving +12% weekly active users.",
                    "Defined roadmap and experiments for AI chat features; uplifted retention by 8%.",
                ],
            ),
        ],
        education=[Education(degree="B.A. Economics", school="DUE", year="2017")],
        projects=[Project(name="Resume Generator", description="Prototype LLM resume tool.", tech=["Python", "LLM"])],
    )
    jd3 = "Looking for PM to lead AI products; strong in prompt engineering, analytics, and experimentation."

    return [
        {"profile": p1, "job_desc": jd1, "filename": "resume_android_automotive.md"},
        {"profile": p2, "job_desc": jd2, "filename": "resume_data_engineer.md"},
        {"profile": p3, "job_desc": jd3, "filename": "resume_ai_pm.md"},
    ]


# ------------------------------- Main ----------------------------------

def ensure_dir(path: str) -> None:
    if not os.path.exists(path):
        os.makedirs(path)


def run_batch(use_llama: bool = True) -> None:
    ensure_dir(OUTPUT_DIR)
    gen = ResumeGenerator()
    samples = sample_profiles()

    logs: List[str] = []
    logs.append("Resume Generation — Batch Run")
    logs.append(f"LLaMA Available: {gen.llama.available}")
    logs.append(f"Model Path: {gen.llama.model_path or '(none)'}\n")

    for i, s in enumerate(samples, start=1):
        result = gen.generate(s["profile"], s["job_desc"], use_llama=use_llama)
        out_path = os.path.join(OUTPUT_DIR, s["filename"])
        with open(out_path, "w", encoding="utf-8") as f:
            f.write(result["resume"])\n
        # Log block
        preview = "\n".join(result["resume"].splitlines()[:12])
        logs.append(f"==== Sample {i} | Engine: {result['engine']} ====")
        logs.append(f"Output: {out_path}")
        logs.append("Preview:\n" + indent(preview, "  "))
        if "error" in result:
            logs.append(f"Error: {result['error']}")
        logs.append("")

    with open(LOGS_FILE, "w", encoding="utf-8") as f:
        f.write("\n".join(logs))


if __name__ == "__main__":
    # No interactive input; run on dummy samples
    run_batch(use_llama=True)
    print(f"Done. Wrote logs to {LOGS_FILE} and outputs to {OUTPUT_DIR}/")
