
# Assignment_03.py — AI-Powered Meeting Summarizer Using Azure OpenAI API
# Author: Generated by M365 Copilot
# Date: 2025-11-30
# Description:
#   - Summarize meeting transcripts using Azure OpenAI (GPT) if credentials are available.
#   - Falls back to a lightweight offline heuristic summarizer when Azure credentials or
#     the OpenAI package are not available, so the script is testable anywhere.
#   - Uses dummy inputs (no interactive input()) and writes sample outputs to a logs file.
#   - Designed as a single, clear Python file per assignment requirements.

from __future__ import annotations
import os
import re
import textwrap
from typing import List, Dict, Optional

LOGS_FILE = "assignment_03_logs.txt"
API_VERSION_DEFAULT = "2024-07-01-preview"  # Azure OpenAI API version


class AzureSummarizer:
    """Wraps Azure OpenAI Chat Completions for meeting summarization.

    If the OpenAI SDK or credentials are missing, `available` will be False
    and `summarize()` will raise RuntimeError. Use OfflineSummarizer instead.
    """

    def __init__(self,
                 endpoint: Optional[str] = None,
                 api_key: Optional[str] = None,
                 deployment: Optional[str] = None,
                 api_version: Optional[str] = None):
        self.endpoint = endpoint or os.getenv("AZURE_OPENAI_ENDPOINT")
        self.api_key = api_key or os.getenv("AZURE_OPENAI_API_KEY")
        self.deployment = deployment or os.getenv("AZURE_DEPLOYMENT_NAME")
        self.api_version = api_version or os.getenv("AZURE_OPENAI_API_VERSION", API_VERSION_DEFAULT)

        self.available = False
        self._client = None
        try:
            from openai import AzureOpenAI  # type: ignore
            if self.endpoint and self.api_key and self.deployment:
                self._client = AzureOpenAI(api_key=self.api_key,
                                           api_version=self.api_version,
                                           azure_endpoint=self.endpoint)
                self.available = True
        except Exception:
            # Missing package or any initialization error -> mark unavailable
            self.available = False

    def summarize(self, transcript: str, temperature: float = 0.2, max_tokens: int = 600) -> str:
        if not self.available:
            raise RuntimeError("AzureSummarizer is not available. Use OfflineSummarizer.")

        system_prompt = (
            "You are a helpful assistant specialized in summarizing meeting notes. "
            "Extract key points, decisions, and action items. Be concise and structured."
        )
        user_prompt = f"Summarize the following meeting transcript with key points, decisions, and action items:\n\n{transcript}"

        resp = self._client.chat.completions.create(
            model=self.deployment,
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_prompt},
            ],
            temperature=temperature,
            max_tokens=max_tokens,
        )
        return resp.choices[0].message.content.strip()


class OfflineSummarizer:
    """A lightweight extractive/heuristic meeting summarizer.

    This is not AI—just rules to make the script runnable without Azure creds.
    It identifies speakers, bullets important lines, infers decisions/action items
    by keywords, and produces a compact structured summary.
    """

    DECISION_KEYS = ["quyết định", "decide", "decision", "chốt", "approve", "phê duyệt"]
    ACTION_KEYS = ["action", "todo", "việc", "làm", "assign", "giao", "deadline", "due"]
    BLOCKER_KEYS = ["blocker", "vấn đề", "issue", "lỗi", "error"]

    def summarize(self, transcript: str) -> str:
        lines = [l.strip() for l in transcript.splitlines() if l.strip()]
        speakers: Dict[str, int] = {}
        bullets: List[str] = []
        decisions: List[str] = []
        actions: List[str] = []
        blockers: List[str] = []

        speaker_pattern = re.compile(r"^(?:\[(?:\d{1,2}:\d{2}\s?[AP]M)?[^\]]*\]\s*)?([A-ZÀ-ỹ][A-Za-zÀ-ỹ]+)\s*:\s*(.+)")

        for ln in lines:
            m = speaker_pattern.match(ln)
            content = ln
            speaker = None
            if m:
                speaker = m.group(1)
                content = m.group(2)
                speakers[speaker] = speakers.get(speaker, 0) + 1

            lc = content.lower()
            # Classify
            if any(k in lc for k in self.DECISION_KEYS):
                decisions.append(self._clean_line(content, speaker))
            if any(k in lc for k in self.ACTION_KEYS):
                actions.append(self._clean_line(content, speaker))
            if any(k in lc for k in self.BLOCKER_KEYS):
                blockers.append(self._clean_line(content, speaker))

            # Key points: keep non-trivial statements
            if len(content.split()) >= 4 and not content.endswith("?"):
                bullets.append(self._clean_line(content, speaker))

        # Deduplicate and trim
        def uniq(seq: List[str]) -> List[str]:
            seen = set()
            out = []
            for s in seq:
                k = s.lower()
                if k not in seen:
                    seen.add(k)
                    out.append(s)
            return out

        bullets = uniq(bullets)[:8]
        decisions = uniq(decisions)[:6]
        actions = uniq(actions)[:8]
        blockers = uniq(blockers)[:6]

        # Build summary
        speaker_stats = ", ".join(f"{name}: {count} turn(s)" for name, count in sorted(speakers.items())) or "N/A"
        wrap = lambda s: textwrap.fill(s, width=96)

        parts: List[str] = []
        parts.append("Meeting Summary (Offline Heuristic)")
        parts.append("Participants Activity: " + speaker_stats)
        parts.append("\nKey Points:")
        if bullets:
            parts.extend([f"- {wrap(bp)}" for bp in bullets])
        else:
            parts.append("- (None detected)")
        parts.append("\nDecisions:")
        if decisions:
            parts.extend([f"- {wrap(d)}" for d in decisions])
        else:
            parts.append("- (None detected)")
        parts.append("\nAction Items:")
        if actions:
            parts.extend([f"- {wrap(a)}" for a in actions])
        else:
            parts.append("- (None detected)")
        parts.append("\nBlockers/Risks:")
        if blockers:
            parts.extend([f"- {wrap(b)}" for b in blockers])
        else:
            parts.append("- (None detected)")

        return "\n".join(parts)

    @staticmethod
    def _clean_line(content: str, speaker: Optional[str]) -> str:
        out = content.strip()
        out = re.sub(r"\s+", " ", out)
        return (f"{speaker}: {out}" if speaker else out)


# --- Sample transcripts (5) for logs/output ---
SAMPLE_TRANSCRIPTS: List[str] = [
    # 1
    """[10:02 AM - Project Sync]
Anna: Chào mọi người, hôm nay mình sẽ cập nhật tiến độ dự án AI chatbot.
Minh: Backend đã xong phần xử lý intent, còn API thì đang test.
Trang: Frontend gặp lỗi hiển thị gợi ý từ chatbot, sẽ fix hôm nay.
Anna: Nhớ cập nhật trên Jira trước chiều nhé. Có gì blocker không?
Minh: Không có gì lớn.
Trang: Mình cần thêm access từ devops để kiểm tra pipeline.
Anna: Quyết định: phát hành bản beta vào thứ Sáu. Action: Huy cấp quyền cho Trang trước 2PM.""",
    # 2
    """[Sprint Review]
Quang: Completed user stories #231 and #245.
Lan: QA found 3 issues related to payment retries.
Quang: Decision: We rollback the payment retry change.
Lan: Action: QA to retest after rollback, deadline hôm nay 5PM.
Huy: Có blocker với môi trường staging, đang down.
Quang: Assign: DevOps khắc phục staging trước trưa.""",
    # 3
    """[11:30 AM - Design Discussion]
My: We should adopt responsive grid for dashboard.
Nam: Approve using CSS Grid over Flex for main layout.
My: Todo: build a prototype by Wednesday.
Nam: No further issues.
My: Decision: keep dark theme by default.""",
    # 4
    """[1:00 PM - Incident Postmortem]
Diep: Error rate spiked due to misconfigured cache TTL.
Bao: Issue resolved, new TTL is 15 minutes.
Diep: Action: add a runbook section and monitoring alert.
Bao: Deadline: tomorrow noon.
Diep: Blocker: missing on-call rotation doc.""",
    # 5
    """[Roadmap Planning]
An: We plan Q1 OKRs: reduce latency by 30%.
Phuong: Decision: prioritize edge caching.
An: Assign: Phuong leads caching track, due next Friday.
Phuong: Risk: vendor API rate limits.
An: Action: set up load tests and alerting.""",
]


def run_batch_and_log(use_azure: bool = True) -> None:
    """Run summarization over SAMPLE_TRANSCRIPTS and write to logs file.

    If Azure is requested but not available, it falls back to offline summarizer.
    """
    azure = AzureSummarizer()
    offline = OfflineSummarizer()

    if use_azure and azure.available:
        summarizer_name = "Azure OpenAI"
        summarize_fn = azure.summarize
    else:
        summarizer_name = "Offline Heuristic"
        summarize_fn = offline.summarize

    outputs: List[str] = []
    for i, t in enumerate(SAMPLE_TRANSCRIPTS, start=1):
        try:
            summary = summarize_fn(t)
        except Exception as e:
            summary = f"[Error summarizing transcript {i}: {e}]\n\nFalling back to Offline summarizer.\n\n" + offline.summarize(t)
        block = (
            f"==== Sample {i} | Engine: {summarizer_name} ===="
            f"\nTranscript:\n{textwrap.indent(t, '  ')}\n\nSummary:\n{textwrap.indent(summary, '  ')}\n\n"
        )
        outputs.append(block)

    with open(LOGS_FILE, "w", encoding="utf-8") as f:
        f.write("AI-Powered Meeting Summarizer — Batch Results\n")
        f.write(f"API Version: {API_VERSION_DEFAULT}\n")
        f.write(f"Azure Available: {AzureSummarizer().available}\n\n")
        for block in outputs:
            f.write(block)


def main() -> None:
    # No interactive input; runs on dummy samples by default
    run_batch_and_log(use_azure=True)
    print(f"Done. Wrote summaries to {LOGS_FILE}")


if __name__ == "__main__":
    main()
